server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
      discovery:
        locator:
          enabled: true # Enable service discovery

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/